hsb2=read.csv('C:\\Users\\aryam\\Desktop\\Fall Sem 2021\\Data Visualization Lab\\LAB 5 31-8-21/hsb2.csv')
attach(hsb2)
library(lattice)
hsb2$ses.f = factor(hsb2$ses, labels=c("low", "middle", "high")) 
colors = c("red", "yellow", "green", "violet", "orange","blue", "pink", "cyan") 
barchart(~write, hsb2,col=colors)
histogram(~write, hsb2,col=colors)
histogram(~write | ses.f, hsb2,col=colors)
densityplot(~socst, hsb2,col=colors)
densityplot(~socst | ses.f, hsb2,col=colors)
qqmath(~write, hsb2,col=colors)
qqmath(~write | ses.f, hsb2,col=colors)
bwplot(~math, hsb2,col=colors)
bwplot(ses.f~math, hsb2,col=colors)
xyplot(write~math, hsb2,col=colors)
xyplot(write~math | ses.f, hsb2,col=colors)
subset <- hsb2[ , 8:12] 
splom(~subset[ , 1:4])
splom(~subset[, 1:3] | subset[, 5])
reg <- lm(write~math+socst+ses.f, hsb2)
par(mfrow=c(3,2))
plot(reg, which=1:2,col=colors)
plot(reg, which=3:4,col=colors)
plot(reg, which=5:6,col=colors)
detach(hsb2)
