mat= c(18,18,29,20,20,29,18)
print(mat)
age=10
print(age)
t=table(mat)
print(t)
mat= c(18,18,19,20,20,19,18,20,19,18)
print(length(mat))
print(table(mat))
df=read.csv("C:\\Users\\aryam\\Desktop\\Fall Sem 2021\\Data Visualization Lab\\LAB 2 10-8-21\\HRDataset_v14.csv")
print(df)
print(ncol(df))
print(length(df))
print(nrow(df))
names(df)
unique(df$MaritalDesc)
barplot(df$Salary)
barplot(df$Salary, main="Salary of Employees", xlab="Employees", ylab="Salary in Rs.")
plot(df$EmpID,df$Salary) # Scatter plot
plot(df$EmpID,df$Salary, type='l')
barplot(table(mat),main="Age Count of 10 Students", xlab="Age",ylab="Count",border="red",col="blue",density=30)
