library(corrplot)
df=read.csv('C:\\Users\\aryam\\Desktop\\Fall Sem 2021\\Data Visualization Lab\\LAB 6 7-9-21/Loan1.csv')
print(df)
print(ncol(df))
print(nrow(df))
cor(df$NoofLoans,df$GoodLoans,method="pearson")
cor(df$NoofLoans,df$GoodLoans,method="spearman")
cor(df$NoofLoans,df$GoodLoans,method="kendall")
cor.test(df$NoofLoans,df$GoodLoans,method="pearson")
M=cor(df)
print(M)

corrplot(M,method='number',type='upper')
corrplot(M,method='number',type='lower')
corrplot(M,method='number')
corrplot(M,method='circle')
corrplot(M,method='pie')
corrplot(M,method='shade')
corrplot(M,method='color')
corrplot(M,method='ellipse')
corrplot(M,method='square')
