library(corrplot)
df=read.csv('C:\\Users\\aryam\\Desktop\\Fall Sem 2021\\Data Visualization Lab\\LAB 6 7-9-21/mtcars.csv')
print(df)
print(ncol(df))
print(nrow(df))
cor(df$mpg,df$wt,method="pearson")
cor(df$mpg,df$wt,method="spearman")
cor(df$mpg,df$wt,method="kendall")
cor.test(df$mpg,df$wt,method="pearson")
sapply(mtcars, class)
M=cor(mtcars[sapply(mtcars, function(x) !is.factor(x))])
print(M)
corrplot(M,method='number',type='upper')
corrplot(M,method='number',type='lower')
corrplot(M,method='number')
corrplot(M,method='circle')
corrplot(M,method='pie')
corrplot(M,method='shade')
corrplot(M,method='color')
corrplot(M,method='ellipse')
corrplot(M,method='square')
