library("readxl")
library(corrplot)
df = read_excel("C:/Users/aryam/Desktop/Fall Sem 2021/Data Visualization Lab/FAT/StudentsPerformance_Dataset.xlsx")
print(ncol(df))
print(nrow(df))
cor(df$reading,df$writing,method="pearson")
cor(df$reading,df$writing,method="spearman")
cor(df$reading,df$writing,method="kendall")
cor.test(df$reading,df$writing,method="pearson")
sapply(df, class)
M=cor(df)
print(M)
corrplot(M,method='number',type='upper')
corrplot(M,method='number',type='lower')
corrplot(M,method='number')
corrplot(M,method='circle')
corrplot(M,method='pie')
corrplot(M,method='shade')
corrplot(M,method='color')
corrplot(M,method='ellipse')
corrplot(M,method='square')
